name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX with latexmk xelatex and biber
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_system_packages: biber
          pre_compile: |
            echo "Using biber for bibliography if needed"
          post_compile: |
            ls -al

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: homework-pdf
          path: |
            main.pdf
